# Autogenerated wrapper script for AWS_MQTT_jll for x86_64-linux-gnu
export libawsmqtt

JLLWrappers.@generate_wrapper_header("AWS_MQTT")
JLLWrappers.@declare_library_product(libawsmqtt, "libaws-c-mqtt.so.1.0.0")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libawsmqtt,
        "lib/libaws-c-mqtt.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
